/**
 * Regenerate the autogenerated block in `docs/reference/cli.md` from the live commander
 * definition. Run via `pnpm docs:gen-cli`.
 */
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

import { buildProgram } from '../../src/cli.js';

const __dirname = fileURLToPath(new URL('.', import.meta.url));
const refFile = path.join(__dirname, '..', 'reference', 'cli.md');

const program = buildProgram();
const help = program.helpInformation();

const content = await readFile(refFile, 'utf8');
const updated = content.replace(
  /<!-- AUTOGEN:BEGIN -->[\s\S]*?<!-- AUTOGEN:END -->/,
  `<!-- AUTOGEN:BEGIN -->\n\n\`\`\`\n${help.trim()}\n\`\`\`\n\n<!-- AUTOGEN:END -->`,
);

await writeFile(refFile, updated, 'utf8');
process.stdout.write(`Wrote ${refFile}\n`);
